use caesar;
insert into role_category (`name`) values ('watcher');
insert into role_category (`name`) values ('itacademy');
insert into role_category (`name`) values ('tes');
insert into role (`name`,category_id) values ('recrouter',1);
insert into role (`name`,category_id) values ('guest',1);
insert into role (`name`,category_id) values ('teacher',2);
insert into role (`name`,category_id) values ('coordinator',2);
insert into role (`name`,category_id) values ('admin',2);
insert into role (`name`,category_id) values ('tes',3);
insert into status_category (`name`) values ('future');
insert into status_category (`name`) values ('current');
insert into status_category (`name`) values ('finished');
insert into `status` (`name`,category_id) values ('planned',1);
insert into `status` (`name`,category_id) values ('boarding',1);
insert into `status` (`name`,category_id) values ('before start',2);
insert into `status` (`name`,category_id) values ('in-process',2);
insert into `status` (`name`,category_id) values ('offering',2);
insert into `status` (`name`,category_id) values ('graduated',3);
insert into specialization (`name`) values ('oop_java_core');
insert into specialization (`name`) values ('js_core');
insert into specialization (`name`) values ('web_C#_.net');
insert into specialization (`name`) values ('testing_ISTQB');
insert into specialization (`name`) values ('HTML5_CSS3_JS_foundamentals');
insert into specialization (`name`) values ('iOS');
insert into specialization (`name`) values ('JAVA');
insert into specialization (`name`) values ('java_for_non_it');
insert into specialization (`name`) values ('.NET');
insert into specialization (`name`) values ('Database');
insert into specialization (`name`) values ('manual_quality_control');
insert into specialization (`name`) values ('ua_c++');
insert into specialization (`name`) values ('automation_testing_quality_control');
insert into specialization (`name`) values ('devops');
insert into specialization (`name`) values ('lamp');
insert into specialization (`name`) values ('web_ui');
insert into specialization (`name`) values ('web_ui_full_stack');
insert into specialization (`name`) values ('UX');
insert into specialization (`name`) values ('ua_web_ui_js');
insert into specialization (`name`) values ('quality_control_for_cloud_computing');
insert into specialization (`name`) values ('angular_boot_camp');
insert into specialization (`name`) values ('ua_go_boot_camp');
insert into specialization (`name`) values ('ua_test_automation_boot_camp_for_mobile_with_python');
insert into specialization (`name`) values ('ua_software_engineering_with_testing');
insert into location (`name`,coordinator_id) values ('Dnipro',NULL);
insert into location (`name`,coordinator_id) values ('Sofia', NULL);
insert into location (`name`) values ('Lviv');
insert into location (`name`) values ('Chernivtsi');
insert into location (`name`) values ('Kyiv');
insert into budget_owner (`name`) values ('SOFTSERVE');
insert into budget_owner (`name`) values ('OPEN GROUP');
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Oleg','Shvets',3,'OlegShvets','ghd22df',1);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Dmytro','Petin',4,'DmytroPetin','fgdfg24sd',1);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Lucas','Lukichich',5,'LukasLukichich','fjgf24sd',2);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Stefan','Vendera',4,'SlavaUkr','asfsdag2',3);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Kozak','Kozachenko',4,'Kozachok','dfgdsg33s',4);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Petro','Poroshenko',4,'Roshenneprodam','zxvfdsg3sa',5);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Mykhaylo','Zadornoff',3,'AmericansAreStupid','asdfsda33d',1);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Volodymyr','Sharapov',3,'IveSadGorbatyi','fdgsdfg4',1);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Ole','Lukoe',3,'OnionRing','dsgagbb42',2);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Milko','Trinichich',3,'MilkoTrilko','cvbxnmdsdf2d',2);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Yulia','Timoshenko',3,'Kosa','dsgacccbbc',5);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Viktor','Fedorovich',3,'Shapka','safsdghds',5);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Renat','Ahmetov',3,'UkrDonaldTrump','asg33w4wfs',5);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Taras','Shevchenko',3,'IveCriedForUkr','gdsfg3fgcccc',3);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Bogdan','Khmelniskiy',3,'SonKiller','sdfgvbcvb32dsf',3);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Bill','Gates',3,'HonoredCitizen',',mnbvcgfd3',4);
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('DP-115',1,'2017-04-29', '2017-08-18',4,7,1, FALSE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('DP-116',1,'2017-04-29', '2017-08-18',6,6,1, TRUE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('DP-111-net',1,'2016-04-30','2016-08-01',6,9,1, FALSE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('SF-120-js',2,'2018-01-10','2018-04-10',1,2,2, FALSE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('CH-116-csh',1,'2017-08-05','2017-11-06',3,3,1, FALSE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('KV-99-db',5,'2017-08-25','2017-12-01',2,10,1, FALSE );
insert into educational_group (`name`,location_id,start_date,finish_date,status_id,specialization_id,budget_owner_id,is_deleted) values ('LV-143-ios',3,'2017-04-28','2017-08-18',5,6,1, FALSE );
insert into expert (edu_group_id, expert_name) values (1, 'Sergey');
insert into expert (edu_group_id,expert_name) values (2,'kristina agilera');
insert into expert (edu_group_id,expert_name) values (4,'Justin Bieber');
insert into expert (edu_group_id,expert_name) values (4,'Selena Gomez');
insert into expert (edu_group_id,expert_name) values (3,'Lyolik');
insert into expert (edu_group_id,expert_name) values (3,'Bolik');
insert into expert (edu_group_id,expert_name) values (5,'Igor Kolomoiskiy');
insert into expert (edu_group_id,expert_name) values (5,'Dmytro Parubiy');
insert into expert (edu_group_id,expert_name) values (6,'Lev Troitskiy');
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Lev','Bukhanets',2,'Myst1c','sdfhs332w',1);
insert into user (first_name,last_name,role_id,nick_name,password_hash_code,location_id) values ('Dmytro','Kholod',2,'DimaKh','sdasdfdew',1);
insert into group_teacher (teacher_id,group_id) values (1,1);
insert into group_teacher (teacher_id,group_id) values (1,2);
insert into group_teacher (teacher_id,group_id) values (11,3);
insert into group_teacher (teacher_id,group_id) values (12,3);
insert into group_teacher (teacher_id,group_id) values (10,4);
insert into group_teacher (teacher_id,group_id) values (18,4);
insert into group_teacher (teacher_id,group_id) values (8,5);
insert into group_teacher (teacher_id,group_id) values (13,5);
insert into group_teacher (teacher_id,group_id) values (14,5);
insert into group_teacher (teacher_id,group_id) values (17,6);
insert into group_teacher (teacher_id,group_id) values (17,6);
insert into event_type (`name`,`is_key_date`) values ('demo',TRUE);
insert into event_type (`name`) values ('lesson');
insert into event_type (`name`,is_key_date) values ('weekly report',true);
insert into event_type (`name`) values ('lecture');
insert into event_type (`name`) values ('consultation');
insert into event_type (`name`) values ('practice');
insert into event_type (`name`) values ('work with expert');
insert into room (`number`,location_id) values ('705',1);
insert into room (`number`,location_id) values ('703',1);
insert into room (`number`,location_id) values ('611',2);
insert into room (`number`,location_id) values ('612',2);
insert into room (`number`,location_id) values ('613',2);
insert into room (`number`,location_id) values ('705',3);
insert into room (`number`,location_id) values ('706-a',3);
insert into room (`number`,location_id) values ('706-b',3);
insert into room (`number`,location_id) values ('505',4);
insert into room (`number`,location_id) values ('502',4);
insert into room (`number`,location_id) values ('501',4);
insert into room (`number`,location_id) values ('311',5);
insert into room (`number`,location_id) values ('312',5);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-24 18:00:00',120,1,2,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-25 18:00:00',120,1,1,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-24 18:00:00',120,2,2,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-25 18:00:00',120,2,1,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-27 17:30:00',60,1,1,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-27 18:30:00',30,1,3,1);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-24 18:00:00',120,6,2,8);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-28 10:00:00',120,6,4,6);
insert into `event` (`datetime`,duration,group_id,event_type_id,room_id) values ('2017-07-29 12:30:00',90,6,5,7);
insert into english_level (name,`level`) values ('elementary',1);
insert into english_level (name,`level`) values ('pre-intermediate',2);
insert into english_level (name,`level`) values ('intermediate',3);
insert into english_level (name,`level`) values ('upper-intermediate',4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Lev','Bukhanets',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Maksym','Kameniev',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Dmytro','Kholod',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Konstantin','Musienko',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Andrii','Serkes',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Vladyslav','Vorontsov',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Anastasiia','Ilina',2,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Roy','Batty',3,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Motoko','Kusanagi',3,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('Daisuke','Aramaki',3,1);
insert into student (first_name,last_name,group_id,english_level_id) values ('Thomas','Anderson',3,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Hans','Landa',3,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('King','Schultz',3,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Ace','Ventura',3,4);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Sarah','Connor',4,2);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Vito','Corleone',4,3);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Luke','Skywalker',4,2);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Rick','Deckard',4,4);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Anton','Chigurh',4,1);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Rocky','Balboa',4,4);
-- insert into student (first_name,last_name,group_id,english_level_id) values ('Jules','Winnfield',4,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Forrest','Gump',5,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Hannibal','Lecter',5,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Jack','Sparrow',5,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Marty','McFly',5,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Darth','Vader',5,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Tyler','Durden',6,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('John','McClane',6,1);
insert into student (first_name,last_name,group_id,english_level_id) values ('Ellen','Ripley',6,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Han','Solo',6,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('James','Bond',6,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Indiana','Jones',6,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('Bruce','Wayne',6,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Andy','Dufresne',6,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('Edward','Scissorhands',7,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Stanley','Ipkiss',7,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Freddy','Krueger',7,2);
insert into student (first_name,last_name,group_id,english_level_id) values ('William','Wallace',7,3);
insert into student (first_name,last_name,group_id,english_level_id) values ('Bruce','Nolan',7,4);
insert into student (first_name,last_name,group_id,english_level_id) values ('Carl','Allen',7,2);
update location set coordinator_id = 2 where `name` = 'Dnipro';
update location set coordinator_id = 3 where `name` = 'Sofia';
update location set coordinator_id = 6 where `name` = 'Lviv';
update location set coordinator_id = 7 where `name` = 'Chernivtsi';
update location set coordinator_id = 8 where `name` = 'Kyiv';
